### ISSUE TITLE
Problem on File "./Minify.py", line 68, in <lambda>

### ISSUE THREAD

**Issue by thegeek** [cgutierrez/JsMinifier#10]
Traceback (most recent call last):
  File "./Minify.py", line 68, in <lambda>
  File "./Minify.py", line 52, in handle_threads
  File "./Minify.py", line 81, in replace
AttributeError: 'GoogleClosureCall' object has no attribute 'error'

Same in Uglyfy_js

Traceback (most recent call last):
  File "./Minify.py", line 68, in <lambda>
  File "./Minify.py", line 52, in handle_threads
  File "./Minify.py", line 81, in replace
AttributeError: 'UglifyCall' object has no attribute 'error'

Just an observation.
When someone clone the git repository in the file Main.sublime-menu on line 33:

```
                                "file": "${packages}/JS Minifier/Minifier.sublime-settings"
```

but the folder cloned is JSMinifier without the space.

Thank You for you attention

**Comment by cgutierrez** [comment]
I updated the path to the settings file to match the repository name. The reason it was like that was because of how I initially named the plugin in the package control plugin.

I am however, unable to replicate the error you're seeing. even after a fresh installation of the plugin. Are you restarting sublime after pulling the updates?  With the naming changes, I'd perhaps try doing a fresh clone and restarting sublime.

**Comment by thegeek** [comment]
Ok I'll try ... i'll keep you posted ...

**Comment by thegeek** [comment]
Ok it work perfectly ... i remove and reclone the repository ... sorry for the false issue ... Btw great plug-in :)
