### ISSUE TITLE
error: Minifier Error: timed out

### ISSUE THREAD

**Issue by keyapril** [cgutierrez/JsMinifier#11]
error: Minifier Error: timed out

**Comment by cgutierrez** [comment]
This error occurs when the minifier API connection timed out... so for some reason, either the Google Closure or Uglify Js web services could not be contacted. This might be a dumb question but were you offline at the time or having any connection issues?

**Comment by vfasky** [comment]
同样遇到该问题 ,  难道是GFW墙掉了?

**Comment by vfasky** [comment]
发现问题了, 在 compilers / googleclosurecall.py line 15
 *.appspot.com 在中国访问是禁止的

## 解决方法:

1.找开 Packages\JsMinifier\Minifier.sublime-settings
2.修改 compiler 的值为 'uglify_js'

enjoy

**Comment by cgutierrez** [comment]
Closing this issue for now as this is an issue with reaching the third party compiler services.

**Comment by q13** [comment]
草，悲催的appspot

**Comment by iamcheyan** [comment]
果真如此...
悲催的国人啊.

**Comment by zfkun** [comment]
感谢天朝!

**Comment by shootsoft** [comment]
先谢国家~

**Comment by griiettner** [comment]
Looks like this is not solved.. I was never able to use this plugin... I always get "Minifier Error: timed out"

**Comment by shershams** [comment]
Getting this error when trying to minify large files. Small files work fine. Any ideas?

**Comment by caizhengda** [comment]
compiler: google_closure Minifier  Error: timed out
compiler: uglify_js Minifier Error: HTTP error 502 contacting API

sos

**Comment by simplees** [comment]
感谢国家，让我能看到这个issues

**Comment by Cleam** [comment]
This is the different！

**Comment by chence** [comment]
compiler: google_closure Minifier Error: timed out
compiler: uglify_js Minifier Error: HTTP error 400 contacting API

**Comment by ikhsan017** [comment]
same here :(

I got this message in every try
`Minifier Error: timed out`

**Comment by ranelpadon** [comment]
This happens to my case also. I'm trying to minify a huge JS file that has around 20,000 lines. But I made it to work. What I did is just modify the Line 28:
timeout=5,

on this file:
https://github.com/cgutierrez/JsMinifier/blob/master/Minify.py

I've changed the timeout value from 5 to 20.
timeout=20,

I've tried setting it to 10 and 15 also but it didn't work; the file to be processed might be too large for the timeout threshold. So if you have more than 20,000 lines you might have to set the timeout to a value higher than 20.

It turned out also that someone has a Pull request for a more flexible, user-configurable value/setting of timeout:
https://github.com/cgutierrez/JsMinifier/pull/21

And for the details of his commit:
https://github.com/cgutierrez/JsMinifier/pull/21/files

**Comment by yokosogithub** [comment]
I have the same problem,the message in sublime:
`Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 440, in is_enabled_
    ret = self.is_enabled()
  File "Nodejs in C:\Users\Rabol\AppData\Roaming\Sublime Text 3\Installed Packages\Nodejs.sublime-package", line 126, in is_enabled
AttributeError: 'NodeUglifyCommand' object has no attribute '_active_file_name'
error: Minifier Error: HTTP error 502 contacting API`
